# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialogue.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def __init__(self, dialogueText):
        super().__init__()
        self.dialogueText = dialogueText

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 276)
        self.dialogueButtonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.dialogueButtonBox.setGeometry(QtCore.QRect(40, 240, 341, 32))
        self.dialogueButtonBox.setOrientation(QtCore.Qt.Horizontal)
        self.dialogueButtonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.dialogueButtonBox.setObjectName("dialogueButtonBox")
        self.dialogueField = QtWidgets.QTextEdit(Dialog)
        self.dialogueField.setGeometry(QtCore.QRect(20, 30, 361, 191))
        self.dialogueField.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.dialogueField.setReadOnly(True)
        self.dialogueField.setObjectName("dialogueField")

        self.retranslateUi(Dialog)
        self.dialogueButtonBox.accepted.connect(Dialog.accept) # type: ignore
        self.dialogueButtonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))

        self.dialogueField.setText(self.dialogueText)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
